### ISSUE TITLE
Mark EOL the application

### ISSUE THREAD

**Issue by yakushabb** [flathub/io.github.Sebicodes99.Prt#12]
@barthalion 

The source code repository seems to have been deleted along with the username.

Could you mark the application as end-of-life (EOL)?

https://github.com/Sebicodes99

**Comment by yakushabb** [comment]
There was a failed attempt: https://github.com/flathub/io.github.Sebicodes99.Prt/pull/10

**Comment by yakushabb** [comment]
@barthalion How can I mark a project as EOL when the developer account and source repository have been deleted?

**Comment by barthalion** [comment]
Handled this directly on the server.
